// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmcPB9fEDfQ4y0ccItvq1eAr7JT_MxePI',
    appId: '1:210374192968:web:b7583702c58f77d8a40d7d',
    messagingSenderId: '210374192968',
    projectId: 'gotogether-e1ada',
    authDomain: 'gotogether-e1ada.firebaseapp.com',
    storageBucket: 'gotogether-e1ada.firebasestorage.app',
    measurementId: 'G-JBERR6HJN5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvVMAaDgzpTwr_Qzk-W39yUuhFek_S2jg',
    appId: '1:210374192968:android:29148d8d2bd66f97a40d7d',
    messagingSenderId: '210374192968',
    projectId: 'gotogether-e1ada',
    storageBucket: 'gotogether-e1ada.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm0MGTn1fDMPyH3lb2qpjiIyz3yuUOIjU',
    appId: '1:210374192968:ios:cc21da0b917d1112a40d7d',
    messagingSenderId: '210374192968',
    projectId: 'gotogether-e1ada',
    storageBucket: 'gotogether-e1ada.firebasestorage.app',
    iosBundleId: 'com.example.gotogether',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm0MGTn1fDMPyH3lb2qpjiIyz3yuUOIjU',
    appId: '1:210374192968:ios:cc21da0b917d1112a40d7d',
    messagingSenderId: '210374192968',
    projectId: 'gotogether-e1ada',
    storageBucket: 'gotogether-e1ada.firebasestorage.app',
    iosBundleId: 'com.example.gotogether',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmcPB9fEDfQ4y0ccItvq1eAr7JT_MxePI',
    appId: '1:210374192968:web:56b9d1874f865bdea40d7d',
    messagingSenderId: '210374192968',
    projectId: 'gotogether-e1ada',
    authDomain: 'gotogether-e1ada.firebaseapp.com',
    storageBucket: 'gotogether-e1ada.firebasestorage.app',
    measurementId: 'G-YEN2GDMPW3',
  );
}
